name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #backend
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Go mod download
        working-directory: ./backend/...
        run: go mod download

      - name: Go build
        working-directory: ./backend/...
        run: go build ./...

      
      - name: Go test
        working-directory: ./backend/...
        run: go test ./...
        
        #frontend
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Frontend build
        working-directory: frontend
        run: npm run build
