name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      proxy: ${{ steps.filter.outputs.proxy }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - backend/**
            frontend:
              - frontend/**
            proxy:
              - reverse-proxy/**


  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.backend == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"

      - name: Go mod download
        run: go mod download

      - name: Go build
        run: go build ./backend/...

      - name: Go test
        run: go test ./backend/...

  docker-build-backend:
    runs-on: ubuntu-latest
    needs: [backend, changes]
    if: needs.changes.outputs.backend == 'true'
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GCP Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2    
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}  
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Build and push docker image
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/backend
          docker build -t $IMAGE:latest -t $IMAGE:$SHA -f backend/Dockerfile .
          docker push $IMAGE:latest
          docker push $IMAGE:$SHA  

      - name: Deploy backend image to Cloud Run
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/backend:$SHA
          gcloud run services update backend-new \
          --image $IMAGE \
          --region europe-north1      
      



  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.frontend == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build
  
        
  docker-build-frontend:
    runs-on: ubuntu-latest
    needs: [changes, frontend]
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GCP Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2    
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}  
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Build and push docker image
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/frontend
          docker build -t $IMAGE:latest -t $IMAGE:$SHA -f frontend/Dockerfile .
          docker push $IMAGE:latest
          docker push $IMAGE:$SHA

      - name: Deploy frontend image to Cloud Run
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/frontend:$SHA
          gcloud run services update frontend-new \
          --image $IMAGE \
          --region europe-north1
            
  
  proxy:
    name: Proxy CI
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.proxy == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.27"

      - name: Go mod download
        run: go mod download

      - name: Go build
        run: go build -o proxy ./reverse-proxy

      - name: Go test
        run: go test ./reverse-proxy/...          

  docker-build-proxy:
    runs-on: ubuntu-latest
    needs: [changes, proxy]
    if: needs.changes.outputs.proxy == 'true'    

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GCP Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2    
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}  
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet

      - name: Build and push docker image
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/reverse-proxy
          docker build -t $IMAGE:latest -t $IMAGE:$SHA -f reverse-proxy/Dockerfile .
          docker push $IMAGE:latest
          docker push $IMAGE:$SHA       

      - name: Deploy proxy image to Cloud Run
        run: |
          SHA=${GITHUB_SHA::7}
          IMAGE=europe-north1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tfwizard-new-location/reverse-proxy:$SHA
          gcloud run services update reverse-proxy-new \
          --image $IMAGE \
          --region europe-north1    
